# ----------------------------------------------------------------------
# Compare Schema Changes
#
# Goal
# ----
# - Compare two versions of JSON Schemas to detect different types of changes.
# - Determine the required semantic version bump (major, minor, patch)
# - Generate a detailed report of schema differences
#
# What it checks
# -------------
# Logic is within `scripts/py/schema_diff.py`:
# 1. Breaking changes that require a major version bump:
#    - Removed properties
#    - Added required fields
#    - Changed property types or constraints
# 2. Non-breaking changes that require a minor version bump:
#    - Added optional properties
#    - Removed required fields
# 3. Documentation changes that require a patch bump:
#    - Updated descriptions
#    - Changed examples or comments
#
# Trigger
# -------
# - Manual trigger only (workflow_dispatch)
# - Requires two Git references to compare:
#   * base_ref: The original/old version (e.g., main, v1.3.11)
#   * target_ref: The new version (e.g., dev, feature/new-schema)
#
# Outcome
# -------
# - Generates schema_diff.json with detailed comparison
# - Always uploads comparison results as an artifact
# ----------------------------------------------------------------------
name: |
  Compare Schema Changes (SemVer Check)

on:
  workflow_dispatch:
    inputs:
      base_ref:
        description: |
          Base reference (e.g., main, v1.3.11) - this is the "old" version
        type: string
        required: true
        default: main
      target_ref:
        description: |
          Target reference (e.g., dev, feature/new-schema) - this is the "new" version
        type: string
        required: true
        default: dev

jobs:
  check-schema-changes:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for comparing branches

      # --------------------------------------------------------------
      # Environment setup
      # --------------------------------------------------------------
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install repo in editable mode
        run: pip install -e .[dev]

      # --------------------------------------------------------------
      # Schema comparison
      # --------------------------------------------------------------
      - name: Create temporary directories for schemas
        run: |
          mkdir -p base_schemas target_schemas

      - name: Extract base schemas
        run: |
          git checkout ${{ inputs.base_ref }}
          cp -r schemas/* base_schemas/
          git checkout -

      - name: Extract target schemas
        run: |
          git checkout ${{ inputs.target_ref }}
          cp -r schemas/* target_schemas/
          git checkout -

      - name: Compare schemas
        run: |
          python scripts/py/schema_diff.py \
            base_schemas \
            target_schemas \
            --output schema_diff.json \
            -v

      - name: Show comparison results
        if: always()
        run: |
          if [ -f schema_diff.json ]; then
            cat schema_diff.json
          else
            echo "'schema_diff.json' not found"
          fi

      # --------------------------------------------------------------
      # Artifacts
      # --------------------------------------------------------------
      - name: Upload comparison results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: schema-diff-report
          path: schema_diff.json
          if-no-files-found: warn